import React, { FC, useRef, useState, useEffect } from 'react'
import Head from 'next/head'
import PageWithLayoutType from '../../types/pageWithLayoutType';
import MainLayout from '../../components/layouts/Main';
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

async function createUser(
  name: string,
  email: string,
  password: string
): Promise<any> {
  const response = await fetch("/api/auth/signup", {
    method: "POST",
    body: JSON.stringify({ name, email, password }),
    headers: {
      "Content-Type": "application/json",
    },
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.message || "Something went wrong!");
  }

  return data;
}

const Signup: FC = (props) => {
  const [formStatus, setFormStatus] = useState<string>();

  const nameInputRef = useRef<HTMLInputElement>(null);
  const emailInputRef = useRef<HTMLInputElement>(null);
  const passwordInputRef = useRef<HTMLInputElement>(null);

  const { status } = useSession();
  const router = useRouter();

  async function submitHandler(event: React.SyntheticEvent) {
    event.preventDefault();

    const enteredName = nameInputRef.current?.value;
    const enteredEmail = emailInputRef.current?.value;
    const enteredPassword = passwordInputRef.current?.value;

    try {
      const result = await createUser(
        enteredName,
        enteredEmail,
        enteredPassword
      );
      console.log(result);
      setFormStatus(`Sign up Success: ${result.message}`);
      router.replace("/login");
    } catch (error: any) {
      console.log(error);
      setFormStatus(`Error Occured: ${error.message}`);
    }
  }

  useEffect(() => {
    let list = document.querySelectorAll('.form-input');

    list.forEach(function(task, index) {
      const input = task.querySelector('input'),
            textarea = task.querySelector('textarea'),
            activeClass = 'active';
      
      let inputItem: any = undefined;

      if (input) inputItem = input;
      if (textarea) inputItem = textarea;

      if (inputItem) {
        inputItem.addEventListener('focus', function () {
          task.classList.add(activeClass)
        });
        
        inputItem.addEventListener('blur', function () {
          if (inputItem.value === '') {
            task.classList.remove(activeClass);
          }
        });
      }
    })        
  }, [])

  if(status === "authenticated") {
    router.replace("/")
    return (
      <div className="main-container">
        <Head>
          <title>Next Blog Signup</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>Signup</h1>
      </div>
    )
  }
  return (
    <div className="main-container">
      <Head>
        <title>Next Blog Signup</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>sign up</h1>
      <form 
        onSubmit={submitHandler}
      >
        <div className='form-input small'>
          <label htmlFor="name">
            name
          </label>
          <input
            id="name"
            type="text"
            required
            autoComplete='false'
            ref={nameInputRef}
          />
        </div>
        <div className='form-input small'>
          <label htmlFor="email">
            email
          </label>
          <input
            id="email"
            type="text"
            required
            autoComplete='false'
            ref={emailInputRef}
          />
        </div>
        <div className='form-input small'>
          <label htmlFor="password">
             password
          </label>
          <input
            id="password"
            type="password"
            required
            autoComplete='false'
            ref={passwordInputRef}
          />
        </div>
        <p>{formStatus}</p>
        <button className='btn' type="submit">
          sign up
        </button>
      </form>
    </div>
  )
}

(Signup as PageWithLayoutType).layout = MainLayout

export default Signup