import React, { FC } from 'react'
import Head from 'next/head'
import PageWithLayoutType from '../../types/pageWithLayoutType';
import MainLayout from '../../components/layouts/Main';

const About: FC = () => {
return (
<div className="main-container">
  <Head>
    <title>Next Blog About</title>
    <meta name="description" content="Generated by create next app" />
  </Head>
  <section className='main-contents__wrapper'>
    <h1>About</h1>
    <p>The Next.js router allows you to do client-side route transitions between pages, similar to a single-page
      application.</p>
  </section>
</div>
)
}

(About as PageWithLayoutType).layout = MainLayout

export default About