import type { NextPage } from 'next'
import Head from 'next/head'
import PageWithLayoutType from '../types/pageWithLayoutType';
import MainLayout from '../components/layouts/Main';

const Home: NextPage = () => {
  return (
<div className="main-container">
      <Head>
        <title>Next Blog Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className='main-contents__wrapper'>
        home
      </section>
    </div>
  )
}

(Home as PageWithLayoutType).layout = MainLayout

export default Home
