import React, { FC } from 'react'
import Head from 'next/head'
import PageWithLayoutType from '../../types/pageWithLayoutType';
import DefaultLayout from '../../components/layouts/Default';

const Dashboard: FC = () => {
  return (
    <div className="main-container">
      <Head>
        <title>Next Blog Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>dashbboard</h1>
    </div>
  )
}

(Dashboard as PageWithLayoutType).layout = DefaultLayout

export default Dashboard